<form name="esewaform" id="esewaform" method="post" action="http://dev.esewa.com.np/epay/main">
            <input value="<?php echo $block->getGrandTotal(); ?>" name="tAmt" type="hidden"> 
			<input value="<?php echo $block->getSubTotal(); ?>" name="amt" type="hidden"> 
			<input value="10" name="txAmt" type="hidden">
			<input value="0" name="psc" type="hidden"> <!--/ product service charge -->
			<input value="0" name="pdc" type="hidden"> <!--/product delivery code -->
			<input value="BECHNUS" name="scd" type="hidden"> <!--/service code -->
			<input value="1000005" name="pid" type="hidden"> <!--/unique id -->
			<input value="<?php echo $block->getSuccessUrl(); ?>" type="hidden" name="su">
			<input value="<?php echo $block->getFailureUrl();?>" type="hidden" name="fu">
</form>
<script type="text/javascript">
require([
        'jquery',
    	], function ($) {
		$(document).ready(function(){
			$('#esewaform').submit();
		});
});
</script>